apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml

helmCharts:
- name: opensearch
  releaseName: opensearch
  repo: https://opensearch-project.github.io/helm-charts/
  version: 2.18.0
  namespace: opensearch
  valuesFile: helm-values.yaml
